import MainHeader from "@/components/main-header/main-header";
import "./globals.css";
import WhatsAppFAB from "@/components/fab/floatActionButton";

export const metadata = {
  title: "Sii media",
  description: "Generated by sii media",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainHeader></MainHeader>
        {children}
        <WhatsAppFAB />
      </body>
    </html>
  );
}
